// <auto-generated />
using System;
using Flats4us.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flats4us.Migrations
{
    [DbContext(typeof(Flats4usContext))]
    [Migration("20230521194717_UserAndModerator")]
    partial class UserAndModerator
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flats4us.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("AccountCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Flat")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Flats4us.Entities.Moderator", b =>
                {
                    b.HasBaseType("Flats4us.Entities.User");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Moderator");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            AccountCreationDate = new DateTime(2023, 5, 11, 21, 47, 17, 869, DateTimeKind.Local).AddTicks(6863),
                            City = "Warszawa",
                            Email = "maciej.kowalski@gmail.com",
                            Flat = 2,
                            LastLoginDate = new DateTime(2023, 5, 21, 21, 47, 17, 869, DateTimeKind.Local).AddTicks(6911),
                            Name = "Maciej",
                            Number = 47,
                            Password = "mkowalski123",
                            PhoneNumber = "456736829",
                            PostalCode = "00-000",
                            Street = "Długa",
                            Surname = "Kowalski",
                            HireDate = new DateTime(2023, 5, 11, 21, 47, 17, 869, DateTimeKind.Local).AddTicks(6913)
                        },
                        new
                        {
                            UserId = 2,
                            AccountCreationDate = new DateTime(2023, 5, 16, 21, 47, 17, 869, DateTimeKind.Local).AddTicks(6916),
                            City = "Gdańsk",
                            Email = "katarzyna.nowak@gmail.com",
                            Flat = 3,
                            LastLoginDate = new DateTime(2023, 5, 20, 21, 47, 17, 869, DateTimeKind.Local).AddTicks(6918),
                            Name = "Katarzyna",
                            Number = 10,
                            Password = "knowak123",
                            PhoneNumber = "512345678",
                            PostalCode = "80-000",
                            Street = "Kwiatowa",
                            Surname = "Nowak",
                            HireDate = new DateTime(2023, 5, 16, 21, 47, 17, 869, DateTimeKind.Local).AddTicks(6920)
                        },
                        new
                        {
                            UserId = 3,
                            AccountCreationDate = new DateTime(2023, 5, 14, 21, 47, 17, 869, DateTimeKind.Local).AddTicks(6922),
                            City = "Kraków",
                            Email = "adam.kowalczyk@gmail.com",
                            Flat = 6,
                            LastLoginDate = new DateTime(2023, 5, 19, 21, 47, 17, 869, DateTimeKind.Local).AddTicks(6924),
                            Name = "Adam",
                            Number = 20,
                            Password = "akowalczyk789",
                            PhoneNumber = "601234567",
                            PostalCode = "30-001",
                            Street = "Słoneczna",
                            Surname = "Kowalczyk",
                            HireDate = new DateTime(2023, 5, 14, 21, 47, 17, 869, DateTimeKind.Local).AddTicks(6925)
                        },
                        new
                        {
                            UserId = 4,
                            AccountCreationDate = new DateTime(2023, 5, 18, 21, 47, 17, 869, DateTimeKind.Local).AddTicks(6928),
                            City = "Warszawa",
                            Email = "magdalena.wojcik@gmail.com",
                            Flat = 2,
                            LastLoginDate = new DateTime(2023, 5, 20, 21, 47, 17, 869, DateTimeKind.Local).AddTicks(6929),
                            Name = "Magdalena",
                            Number = 15,
                            Password = "mwojcik456",
                            PhoneNumber = "712345678",
                            PostalCode = "02-000",
                            Street = "Ogrodowa",
                            Surname = "Wójcik",
                            HireDate = new DateTime(2023, 5, 18, 21, 47, 17, 869, DateTimeKind.Local).AddTicks(6931)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
