import { Injectable } from '@angular/core';
import { IFlatOffer } from '../models/start-site.models';

@Injectable()
export class StartService {
	public allFlatOffers: IFlatOffer[] = [
		{
			regionCity: { region: 'mazowieckie', city: 'Warszawa' },
			district: 'Bemowo',
			price: 2500,
			rent: 500,
			area: 35,
			rooms: 3,
			url: '/',
			imgSource: './assets/mieszkanie.jpg',
			type: 'Mieszkanie',
		},
		{
			regionCity: { region: 'mazowieckie', city: 'Warszawa' },
			district: 'Wola',
			price: 2000,
			rent: 700,
			area: 30,
			rooms: 2,
			url: '#',
			imgSource: './assets/mieszkanie.jpg',
			type: 'Mieszkanie',
		},
		{
			regionCity: { region: 'mazowieckie', city: 'Warszawa' },
			district: 'Mokotów',
			price: 3000,
			rent: 900,
			area: 40,
			rooms: 3,
			url: '/',
			imgSource: './assets/mieszkanie.jpg',
			type: 'Mieszkanie',
		},
		{
			regionCity: { region: 'mazowieckie', city: 'Warszawa' },
			district: 'Białołęka',
			price: 1200,
			rent: 300,
			area: 25,
			rooms: 1,
			url: '/',
			imgSource: './assets/mieszkanie.jpg',
			type: 'Pokój',
		},
		{
			regionCity: { region: 'mazowieckie', city: 'Warszawa' },
			district: 'Wawer',
			price: 1700,
			rent: 900,
			area: 30,
			rooms: 2,
			url: '/',
			imgSource: './assets/mieszkanie.jpg',
			type: 'Mieszkanie',
		},
		{
			regionCity: { region: 'mazowieckie', city: 'Warszawa' },
			district: 'Śródmieście',
			price: 2000,
			rent: 1000,
			area: 37,
			rooms: 3,
			url: '/',
			imgSource: './assets/mieszkanie.jpg',
			type: 'Mieszkanie',
		},
		{
			regionCity: { region: 'mazowieckie', city: 'Warszawa' },
			district: 'Bemowo',
			price: 2500,
			rent: 500,
			area: 35,
			rooms: 3,
			url: '/',
			imgSource: './assets/mieszkanie.jpg',
			type: 'Mieszkanie',
		},
		{
			regionCity: { region: 'mazowieckie', city: 'Warszawa' },
			district: 'Wola',
			price: 2000,
			rent: 700,
			area: 30,
			rooms: 2,
			url: '#',
			imgSource: './assets/mieszkanie.jpg',
			type: 'Mieszkanie',
		},
		{
			regionCity: { region: 'mazowieckie', city: 'Warszawa' },
			district: 'Mokotów',
			price: 3000,
			rent: 900,
			area: 40,
			rooms: 3,
			url: '/',
			imgSource: './assets/mieszkanie.jpg',
			type: 'Mieszkanie',
		},
		{
			regionCity: { region: 'mazowieckie', city: 'Warszawa' },
			district: 'Białołęka',
			price: 1200,
			rent: 300,
			area: 25,
			rooms: 1,
			url: '/',
			imgSource: './assets/mieszkanie.jpg',
			type: 'Pokój',
		},
		{
			regionCity: { region: 'mazowieckie', city: 'Warszawa' },
			district: 'Wawer',
			price: 1700,
			rent: 900,
			area: 30,
			rooms: 2,
			url: '/',
			imgSource: './assets/mieszkanie.jpg',
			type: 'Mieszkanie',
		},
		{
			regionCity: { region: 'mazowieckie', city: 'Warszawa' },
			district: 'Śródmieście',
			price: 2000,
			rent: 1000,
			area: 37,
			rooms: 3,
			url: '/',
			imgSource: './assets/mieszkanie.jpg',
			type: 'Mieszkanie',
		},
	];
}
