export enum NotificationType {
	NEW_MEETING_PROPOSITION_TITLE = 'new-meeting-proposition-title',
	NEW_MEETING_PROPOSITION_BODY = 'new-meeting-proposition-body',
	MEETING_PROPOSITION_ACCEPTED_TITLE = 'meeting-proposition-accepted-title',
	MEETING_PROPOSITION_ACCEPTED_BODY = 'meeting-proposition-accepted-body',
	MEETING_PROPOSITION_REJECTED_TITLE = 'meeting-proposition-rejected-title',
	MEETING_PROPOSITION_REJECTED_BODY = 'meeting-proposition-rejected-body',
	NEW_MATCH_TITLE = 'new-match-title',
	NEW_MATCH_BODY = 'new-match-body',
	NEW_PAYMENT_TITLE = 'new-payment-title',
	NEW_PAYMENT_BODY = 'new-payment-body',
	NEW_RENT_PROPOSITION_TITLE = 'new-rent-proposition-title',
	NEW_RENT_PROPOSITION_BODY = 'new-rent-proposition-body',
	RENT_PROPOSITION_ACCEPTED_TITLE = 'rent-proposition-accepted-title',
	RENT_PROPOSITION_ACCEPTED_BODY = 'rent-proposition-accepted-body',
	RENT_PROPOSITION_REJECTED_TITLE = 'rent-proposition-rejected-title',
	RENT_PROPOSITION_REJECTED_BODY = 'rent-proposition-rejected-body',
}
