name: Lint and Format Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Change working directory
        run: |
          cd ./angular

      - name: Set up Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16.x'

      - name: Install dependencies
        working-directory: ./angular
        run: |
          npm install

      - name: Run ESLint
        working-directory: ./angular
        run: npm run lint

      - name: Run Prettier check
        working-directory: ./angular
        run: npm run prettier:check
