on:
  pull_request:
  push:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Change working directory
        run: |
          cd ./Flats4us-frontend

      - name: Set up Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: "16.x"

      - name: Install dependencies
        working-directory: ./Flats4us-frontend
        run: |
          npm install

      - name: Run ESLint
        working-directory: ./Flats4us-frontend
        run: npm run lint

      - name: Run Prettier
        working-directory: ./Flats4us-frontend
        run: npm run prettier:check
